import type { FilmPreset, FilterParams } from '../filters/types'

export const presets: FilmPreset[] = [
  {
    id: 'kodak-portra-400',
    name: 'Kodak Portra 400',
    nameZh: 'Portra 400',
    description: '经典人像胶片，暖色调，柔和高光，优雅肤色',
    i18nKey: 'kodakPortra400',
    params: {
      colorGrade: {
        temperature: 25, tint: 5, saturation: -15, contrast: -10,
        exposure: 0, highlights: -10, shadows: 8,
        midtoneR: 5, midtoneG: 2, midtoneB: -3,
        shadowR: 20, shadowG: 8, shadowB: -5,
        highlightR: -5, highlightG: -3, highlightB: 5,
      },
      grain: { intensity: 12, size: 1.5, colorVariance: 15, shadowBoost: 25, highlightReduction: 40 },
      vignette: { intensity: 18, radius: 1.2, feather: 60, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-right' },
      fade: { intensity: 15 },
      halation: { intensity: 20, color: 'warm', radius: 10 },
      bloom: { intensity: 0, threshold: 80, radius: 8 },
      toneCurve: { shadows: 5, midtones: 0, highlights: -5 },
    },
  },
  {
    id: 'kodak-gold-200',
    name: 'Kodak Gold 200',
    nameZh: 'Gold 200',
    description: '浓郁暖调，高饱和度，适合日常与旅行',
    i18nKey: 'kodakGold200',
    params: {
      colorGrade: {
        temperature: 35, tint: 8, saturation: 15, contrast: 8,
        exposure: 5, highlights: -15, shadows: 10,
        midtoneR: 8, midtoneG: 3, midtoneB: -5,
        shadowR: 25, shadowG: 15, shadowB: -10,
        highlightR: 10, highlightG: 5, highlightB: -5,
      },
      grain: { intensity: 18, size: 1.2, colorVariance: 15, shadowBoost: 25, highlightReduction: 35 },
      vignette: { intensity: 30, radius: 1.1, feather: 50, color: 0 },
      lightLeak: { intensity: 15, color: 'warm', position: 'top-left' },
      fade: { intensity: 10 },
      halation: { intensity: 35, color: 'gold', radius: 12 },
      bloom: { intensity: 10, threshold: 75, radius: 10 },
      toneCurve: { shadows: 0, midtones: 5, highlights: -8 },
    },
  },
  {
    id: 'fuji-superia-400',
    name: 'Fuji Superia 400',
    nameZh: 'Superia 400',
    description: '清新绿调，冷暖平衡，出色的肤色还原',
    i18nKey: 'fujiSuperia400',
    params: {
      colorGrade: {
        temperature: -10, tint: -8, saturation: 5, contrast: 5,
        exposure: 0, highlights: -5, shadows: 5,
        midtoneR: -3, midtoneG: 5, midtoneB: -2,
        shadowR: -5, shadowG: 15, shadowB: 5,
        highlightR: 5, highlightG: -2, highlightB: -3,
      },
      grain: { intensity: 22, size: 1, colorVariance: 20, shadowBoost: 30, highlightReduction: 35 },
      vignette: { intensity: 15, radius: 1.3, feather: 65, color: 0 },
      lightLeak: { intensity: 0, color: 'cool', position: 'bottom-right' },
      fade: { intensity: 8 },
      halation: { intensity: 10, color: 'warm', radius: 8 },
      bloom: { intensity: 0, threshold: 80, radius: 8 },
      toneCurve: { shadows: 3, midtones: 2, highlights: -3 },
    },
  },
  {
    id: 'fuji-c200',
    name: 'Fuji C200',
    nameZh: 'C200',
    description: '清淡冷调，低对比度，日系清新风格',
    i18nKey: 'fujiC200',
    params: {
      colorGrade: {
        temperature: -15, tint: -5, saturation: -10, contrast: -15,
        exposure: -5, highlights: -20, shadows: 15,
        midtoneR: -2, midtoneG: 3, midtoneB: 5,
        shadowR: -5, shadowG: 5, shadowB: 15,
        highlightR: 3, highlightG: 3, highlightB: 8,
      },
      grain: { intensity: 15, size: 1, colorVariance: 10, shadowBoost: 20, highlightReduction: 50 },
      vignette: { intensity: 10, radius: 1.4, feather: 70, color: 0 },
      lightLeak: { intensity: 8, color: 'cool', position: 'top-right' },
      fade: { intensity: 25 },
      halation: { intensity: 5, color: 'warm', radius: 8 },
      bloom: { intensity: 15, threshold: 70, radius: 12 },
      toneCurve: { shadows: 8, midtones: 3, highlights: -10 },
    },
  },
  {
    id: 'ilford-hp5',
    name: 'Ilford HP5 Plus',
    nameZh: 'HP5 黑白',
    description: '经典黑白胶片，高对比度，浓郁颗粒感',
    i18nKey: 'ilfordHP5',
    params: {
      colorGrade: {
        temperature: 0, tint: 0, saturation: -100, contrast: 25,
        exposure: 0, highlights: -20, shadows: 10,
        midtoneR: 0, midtoneG: 0, midtoneB: 0,
        shadowR: 0, shadowG: 0, shadowB: 0,
        highlightR: 0, highlightG: 0, highlightB: 0,
      },
      grain: { intensity: 65, size: 2, colorVariance: 0, shadowBoost: 50, highlightReduction: 20 },
      vignette: { intensity: 45, radius: 1.0, feather: 40, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-left' },
      fade: { intensity: 12 },
      halation: { intensity: 0, color: 'warm', radius: 8 },
      bloom: { intensity: 0, threshold: 80, radius: 8 },
      toneCurve: { shadows: -5, midtones: 0, highlights: 5 },
    },
  },
  {
    id: 'kodak-ektar-100',
    name: 'Kodak Ektar 100',
    nameZh: 'Ektar 100',
    description: '超高饱和度风景胶片，极细颗粒，鲜艳色彩',
    i18nKey: 'kodakEktar100',
    params: {
      colorGrade: {
        temperature: 8, tint: 3, saturation: 45, contrast: 22,
        exposure: 5, highlights: -12, shadows: 8,
        midtoneR: 5, midtoneG: 2, midtoneB: -3,
        shadowR: 10, shadowG: 5, shadowB: -8,
        highlightR: 5, highlightG: 0, highlightB: -5,
      },
      grain: { intensity: 4, size: 0.7, colorVariance: 8, shadowBoost: 10, highlightReduction: 30 },
      vignette: { intensity: 12, radius: 1.3, feather: 65, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-right' },
      fade: { intensity: 3 },
      halation: { intensity: 8, color: 'warm', radius: 6 },
      bloom: { intensity: 5, threshold: 85, radius: 6 },
      toneCurve: { shadows: -3, midtones: 3, highlights: -5 },
    },
  },
  {
    id: 'fuji-velvia-50',
    name: 'Fuji Velvia 50',
    nameZh: 'Velvia 50',
    description: '反转片，极致饱和，深邃蓝绿，高对比',
    i18nKey: 'fujiVelvia50',
    params: {
      colorGrade: {
        temperature: -12, tint: 5, saturation: 65, contrast: 32,
        exposure: 0, highlights: -18, shadows: 5,
        midtoneR: 3, midtoneG: 5, midtoneB: 8,
        shadowR: -8, shadowG: 5, shadowB: 15,
        highlightR: 3, highlightG: 2, highlightB: -5,
      },
      grain: { intensity: 3, size: 0.7, colorVariance: 5, shadowBoost: 8, highlightReduction: 40 },
      vignette: { intensity: 18, radius: 1.2, feather: 55, color: 0 },
      lightLeak: { intensity: 0, color: 'cool', position: 'top-left' },
      fade: { intensity: 0 },
      halation: { intensity: 5, color: 'warm', radius: 6 },
      bloom: { intensity: 8, threshold: 80, radius: 8 },
      toneCurve: { shadows: -8, midtones: 5, highlights: -8 },
    },
  },
  {
    id: 'cinestill-800t',
    name: 'CineStill 800T',
    nameZh: 'CineStill 800T',
    description: '电影胶片，钨丝灯色调，蓝冷阴影，标志性红色光晕',
    i18nKey: 'cinestill800t',
    params: {
      colorGrade: {
        temperature: -30, tint: -5, saturation: 5, contrast: 18,
        exposure: 5, highlights: -8, shadows: 12,
        midtoneR: 8, midtoneG: 3, midtoneB: 15,
        shadowR: -8, shadowG: -5, shadowB: 25,
        highlightR: 12, highlightG: 5, highlightB: -8,
      },
      grain: { intensity: 48, size: 1.8, colorVariance: 20, shadowBoost: 40, highlightReduction: 25 },
      vignette: { intensity: 28, radius: 1.1, feather: 45, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-right' },
      fade: { intensity: 8 },
      halation: { intensity: 65, color: 'red', radius: 18 },
      bloom: { intensity: 20, threshold: 70, radius: 14 },
      toneCurve: { shadows: 5, midtones: 0, highlights: -5 },
    },
  },
  {
    id: 'kodak-trix-400',
    name: 'Kodak Tri-X 400',
    nameZh: 'Tri-X 400',
    description: '经典新闻黑白胶片，高对比，粗糙颗粒，戏剧张力',
    i18nKey: 'kodakTriX400',
    params: {
      colorGrade: {
        temperature: 0, tint: 0, saturation: -100, contrast: 38,
        exposure: 0, highlights: -15, shadows: 5,
        midtoneR: 0, midtoneG: 0, midtoneB: 0,
        shadowR: 0, shadowG: 0, shadowB: 0,
        highlightR: 0, highlightG: 0, highlightB: 0,
      },
      grain: { intensity: 55, size: 1.8, colorVariance: 0, shadowBoost: 60, highlightReduction: 15 },
      vignette: { intensity: 38, radius: 1.05, feather: 38, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-left' },
      fade: { intensity: 5 },
      halation: { intensity: 0, color: 'warm', radius: 8 },
      bloom: { intensity: 0, threshold: 80, radius: 8 },
      toneCurve: { shadows: -8, midtones: 0, highlights: 8 },
    },
  },
  {
    id: 'agfa-vista-200',
    name: 'Agfa Vista 200',
    nameZh: 'Agfa Vista 200',
    description: '温暖复古，自然褪色，偏品红阴影，胶片怀旧感',
    i18nKey: 'agfaVista200',
    params: {
      colorGrade: {
        temperature: 20, tint: 12, saturation: 10, contrast: -8,
        exposure: 0, highlights: -10, shadows: 12,
        midtoneR: 8, midtoneG: 3, midtoneB: -5,
        shadowR: 15, shadowG: -5, shadowB: 8,
        highlightR: 5, highlightG: 3, highlightB: -3,
      },
      grain: { intensity: 32, size: 1.3, colorVariance: 22, shadowBoost: 30, highlightReduction: 35 },
      vignette: { intensity: 22, radius: 1.2, feather: 55, color: 0 },
      lightLeak: { intensity: 20, color: 'warm', position: 'top-left' },
      fade: { intensity: 28 },
      halation: { intensity: 15, color: 'warm', radius: 10 },
      bloom: { intensity: 5, threshold: 75, radius: 8 },
      toneCurve: { shadows: 8, midtones: 3, highlights: -3 },
    },
  },
  {
    id: 'fuji-eterna-500',
    name: 'Fuji Eterna 500',
    nameZh: 'Eterna 500',
    description: '电影负片，低饱和，暗部细腻，高光柔和，电影感十足',
    i18nKey: 'fujiEterna500',
    params: {
      colorGrade: {
        temperature: -5, tint: 3, saturation: -25, contrast: -12,
        exposure: 0, highlights: -22, shadows: 18,
        midtoneR: 3, midtoneG: 2, midtoneB: 5,
        shadowR: 5, shadowG: 5, shadowB: 12,
        highlightR: 3, highlightG: 3, highlightB: 5,
      },
      grain: { intensity: 38, size: 1.5, colorVariance: 12, shadowBoost: 35, highlightReduction: 45 },
      vignette: { intensity: 20, radius: 1.25, feather: 62, color: 0 },
      lightLeak: { intensity: 0, color: 'warm', position: 'top-right' },
      fade: { intensity: 32 },
      halation: { intensity: 12, color: 'warm', radius: 10 },
      bloom: { intensity: 18, threshold: 72, radius: 12 },
      toneCurve: { shadows: 10, midtones: 2, highlights: -12 },
    },
  },
]

export function getPresetById(id: string): FilmPreset | undefined {
  return presets.find((p) => p.id === id)
}

export function cloneParams(params: FilterParams): FilterParams {
  return JSON.parse(JSON.stringify(params))
}
